### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by sanbales** [nwroyer/Python-Military-Symbols#3]
# Intro
First of all, I'd like to say thank you for making this library.  It's really good.

I made a [Jupyter Widget](https://gist.github.com/sanbales/b68989ddb3df37671a7c45d1bf29c9cc) to play around with interactively making the symbols.

When making symbols though, I noticed some (potential) issues.

# Potential Issues Found
## Friendly Satellites
> Show `pink` instead of `blue`

![image](https://user-images.githubusercontent.com/1438114/230167215-327b4894-9cca-42e3-ae20-471a3444830c.png)

## Reconnaissance Satellites
> Show as recon unit instead of a recon satellite symbol

![image](https://user-images.githubusercontent.com/1438114/230167436-7ee709a4-622e-4a19-99cb-deae110128dc.png)

**Comment by nwroyer** [comment]
Thanks for reaching out! It's been a while since I touched this due to life getting in the way, but here's a general breakdown and some notes on the identified issues:

# Pink satellite

I don't think this is actually a bug per se - the match weight of both the military satellite and civilian satellite base symbols are equal, so it's defaulting to the lowest-numbered one, in this case the civilian satellite (hence the pink coloring). While this is working as intended in terms of the code, I agree with you that more users of the package are likely to want to default to a military satellite, so I've adjusted the match weight accordingly and can confirm it now defaults to the military satellite on my local machine. 

# Friendly reconnaissance satellite bug

For your second issue specifically, I believe that the fuzzy-matcher used for strings (located at `name_to_sidc.py`) is the culprit. Can you add an output indicating the SIDC for the field you select via dropdown? If it's exposing the wrong SIDC for the name, but the right SIDC for the displayed symbol, that'll help confirm that hypothesis. If it's showing the wrong symbol but is guessing the right SIDC, then the issue is almost certainly in `get_svg` at line 196 of `individual_symbol.py`; that's where all the SVG-composing code goes. Printing a `dir` dump of the symbol will indicate where the issue is coming from - but since it's jumping to a reconnaissance asset, I suspect the issue is with the matching picking up on the "reconnaissance" keyword, and because the entire 10-series symbols for land units are weighted higher than the space symbols, terminating early. 

Are you able to confirm that the friendly reconnaissance satellite is displayed wrong if you compute it directly from a SIDC (`30030500001115000000`)? 

I'm able to get the correct symbol when running the command-line wrapper of the tool with `military_symbol -n "reconnaissance satellite"`. What string is your tool actually passing to the library? Just typing in "reconnaissance" on the command line will give the basic land recon unit symbol, so I wonder if the full string is not getting passed in somehow. 

## Structure

`individual_symbol.py` handles only the individual symbols in an abstract sense; it basically contains all the different fields and handles going from SIDC <-> symbol object and vice versa, as well as exposing a few convenience functions. `get_svg` at line 196 is what handles the generation of SVG representations. 

`symbol_schema.py` is the registry for all the symbol elements, and parses `symbols.json` to load both the SVG source and the logical structure of the symbols; the JSON essentially embeds not only the entire symbol catalog of the 2525D standard but also weights for matching the names of the symbols. Line 453 of `symbol_schema` has `load_entity`, which focuses on loading the symbols from JSON, and where I suspect the problem might be if the SIDC is incorrect.
